Repository kubernetes/test-infra, pull requests merged in 2018-02, with the labels that each got.

#6716 Add spell check
  Gopkg.lock
  Gopkg.toml
  hack/prune-libraries.sh
  hack/verify-spelling.sh
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
  vendor/BUILD
  vendor/github.com/client9/misspell/.gitignore
  vendor/github.com/client9/misspell/.travis.yml
  vendor/github.com/client9/misspell/BUILD
  vendor/github.com/client9/misspell/Dockerfile
  vendor/github.com/client9/misspell/Gopkg.lock
  vendor/github.com/client9/misspell/Gopkg.toml
  vendor/github.com/client9/misspell/LICENSE
  vendor/github.com/client9/misspell/Makefile
  vendor/github.com/client9/misspell/README.md
  vendor/github.com/client9/misspell/RELEASE-HOWTO.md
  vendor/github.com/client9/misspell/ascii.go
  vendor/github.com/client9/misspell/case.go
  vendor/github.com/client9/misspell/cmd/misspell/BUILD
  vendor/github.com/client9/misspell/cmd/misspell/main.go
  vendor/github.com/client9/misspell/goreleaser.yml
  vendor/github.com/client9/misspell/install-misspell.sh
  vendor/github.com/client9/misspell/legal.go
  vendor/github.com/client9/misspell/mime.go
  vendor/github.com/client9/misspell/notwords.go
  vendor/github.com/client9/misspell/replace.go
  vendor/github.com/client9/misspell/stringreplacer.go
  vendor/github.com/client9/misspell/stringreplacer_test.gox
  vendor/github.com/client9/misspell/url.go
  vendor/github.com/client9/misspell/words.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6760 Wrap hack/verify-spelling in a bazel test
  hack/BUILD
  hack/verify-spelling.sh
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6598 Create a configuration for tf/minigo
  prow/config.yaml
  prow/plugins.yaml
  testgrid/cmd/config/config_test.go
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6743 switch planter default to 0.10.0
  planter/Makefile
  planter/planter.sh
Labels: approved, area/planter, cncf-cla: yes, lgtm, size/XS

#6763 bind docker credential to cadvisor-canarypush job
  prow/config.yaml
  scenarios/canarypush.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#6735 support extract gke latest from per release version
  kubetest/extract_k8s.go
  kubetest/gke.go
  kubetest/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#6740 Adds new page for plugin help reference
  prow/cmd/deck/static/command-help.html
  prow/cmd/deck/static/index.html
  prow/cmd/deck/static/plugins-script.js
  prow/cmd/deck/static/plugins.html
  prow/cmd/deck/static/style.css
  prow/cmd/deck/static/tide.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#6765 s/gcloud docker -- push/docker push/g everywhere in test-infra
  boskos/Makefile
  gcsweb/Makefile
  images/bazelbuild/Makefile
  images/bigquery/Makefile
  images/bootstrap/Makefile
  images/gcloud/Makefile
  images/heapster/Makefile
  images/kubeadm/Makefile
  images/kubekins-e2e/Makefile
  images/kubekins-test/Makefile
  images/pull-test-infra-gubernator/Makefile
  kettle/Makefile
  logexporter/Makefile
  maintenance/aws-janitor/Makefile
  mungegithub/Makefile
  mungegithub/issue_labeler/deploy.sh
  planter/Makefile
  queue_health/common.mk
  triage/Makefile
  velodrome/fetcher/Makefile
  velodrome/token-counter/Makefile
  velodrome/transform/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#6764 kanary gke staging change
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6768 Clarifying no name/query error in config test
  testgrid/cmd/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#6748 fix typo
  ghclient/wrappers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6762 migratestatus: change --modify to --dry-run and update docs
  maintenance/migratestatus/README.md
  maintenance/migratestatus/migrate-many.sh
  maintenance/migratestatus/migratestatus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6750 Fix typo
  experiment/tracer/trace.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6747 fix typo skiped -> skipped, indeces -> indices
  gubernator/github/classifier.py
  gubernator/kubelet_parser.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6746 Update README.md
  velodrome/fetcher/README.md
  velodrome/token-counter/token-counter.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6744 Fix typo repects -> respects
  planter/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6741 Create gce ingress scale job and add to sig-network dashboard
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6761 Adding PR jobs for kube-deploy
  jobs/config.json
  prow/config.yaml
  prow/plugins.yaml
  testgrid/cmd/config/config_test.go
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6672 Adding scripts to create a kubetest image with kubemci
  images/kubemci/Dockerfile
  images/kubemci/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#6770 For ingress upgrade test, start cluster with glbc 0.9.7
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6772 Fixes command help table goes off the screen
  prow/cmd/deck/static/command-help.html
  prow/cmd/deck/static/style.css
Labels: approved, cncf-cla: yes, lgtm, size/S

#6753 Make Tide get all open PRs with one search query instead of one per Tide query.
  prow/config/BUILD.bazel
  prow/config/tide.go
  prow/config/tide_test.go
  prow/tide/tide.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#6749 check build exists before make actual build
  scenarios/kubernetes_build.py
Labels: approved, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#6775 fix kops-build image
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6783 Revert "Make gke-large-deploy manual again"
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6650 Add multicluster federation release job.
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6784 Add graphviz package to kubekins image for graphing profiles
  images/kubekins-e2e/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6786 Modify gke-large-deploy to run 5k-node cluster & use custom subnet
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6785 Bump kubekins image
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  prow/config.yaml
  scenarios/kubernetes_e2e.py
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6782 Enable Metadata Agent in Stackdriver monitoring e2e tests
  jobs/env/ci-kubernetes-e2e-gce-stackdriver.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6779 Add prow jobs for new Kubeflow repositories:
  prow/config.yaml
  prow/plugins.yaml
  testgrid/cmd/config/config_test.go
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6701 Add some user docs for branchprotector
  prow/cmd/branchprotector/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#6780 fixconfig: use tempfile in the same directory as the output file
  maintenance/fixconfig/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6771 Update Minigo-prow config so that we can use bootstrap.py
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6769 Fix extract gke regex to allow --extract=gke-latest-1.7
  kubetest/extract_k8s.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#6790 Migrate a few missing pieces to BUILD.bazel
  README.md
  hack/prune-libraries.sh
  hack/update-bazel.sh
  metrics/bigquery_test.py
  prow/plugins/buildifier/buildifier.go
  prow/plugins/buildifier/buildifier_test.go
Labels: approved, area/bazel, cncf-cla: yes, lgtm, size/S

#6787 Add testing image for kube-deploy with etcd installed
  images/kube-deploy/Dockerfile
  images/kube-deploy/Makefile
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6791 bump gke-staging targets & clean up stale jobs
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6794 Fix typo: Update minigo test harness image to v2
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6795 Fix more minigo test config typos
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6793 Change gke-large perf jobs to n1-standard-1 and run correctness suite on large-deploy
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6796 Temporarily make ci-ingress-gce-e2e run serially
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6797 Enable pushing metrics from hook
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6767 use per WORKSPACE / host tools keyed bazel cache(s)
  experiment/BUILD.bazel
  experiment/nursery/BUILD.bazel
  experiment/nursery/README.md
  experiment/nursery/create_bazel_cache_rcs.sh
  experiment/nursery/deployment.yaml
  experiment/nursery/diskcache/BUILD.bazel
  experiment/nursery/diskcache/cache.go
  experiment/nursery/diskcache/cache_test.go
  experiment/nursery/main.go
Labels: approved, area/bazel, cncf-cla: yes, lgtm, size/XL

#6788 Adds missing meta tags to Deck's html files
  prow/cmd/deck/static/command-help.html
  prow/cmd/deck/static/index.html
  prow/cmd/deck/static/plugins.html
  prow/cmd/deck/static/tide.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6802 Correct configs for gke-large-deploy and gke-scale-correctness
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6724 Autoscaler VPA recommender e2e tests specified.
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6805 Change GKE scale jobs schedule
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6806 pull request process link points at contrib guide
  prow/plugins/approve/approve_test.go
  prow/plugins/approve/approvers/approvers_test.go
  prow/plugins/approve/approvers/owners.go
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/S

#6798 apicoverage: Add --minimum-coverage option
  experiment/coverage/apicoverage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6778 Minor updates to deck UI
  prow/cmd/deck/static/plugins.html
  prow/cmd/deck/static/script.js
  prow/cmd/deck/static/style.css
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#6799 Adding a CI job to push kubemci image
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6006 planter.sh should not mount user home
  planter/planter.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#6809 planter: remove npm cache mount and ensure bazel cache dir exists
  planter/planter.sh
Labels: approved, area/planter, cncf-cla: yes, lgtm, size/S

#6739 Fix approval comment links to markdown files with OWNERS headers.
  prow/plugins/approve/approve_test.go
  prow/plugins/approve/approvers/approvers_test.go
  prow/plugins/approve/approvers/owners.go
  prow/plugins/approve/approvers/owners_test.go
  prow/repoowners/repoowners.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6810 Added a new periodic job to run ingress tests in ipvs mode
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6811 hack/verify-bazel: disallow BUILD files except in vendor/
  hack/prune-libraries.sh
  hack/verify-bazel.sh
  vendor/k8s.io/api/core/v1/BUILD
  vendor/k8s.io/apimachinery/pkg/api/equality/BUILD
  vendor/k8s.io/apimachinery/pkg/api/resource/BUILD
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD
  vendor/k8s.io/apimachinery/pkg/conversion/BUILD
  vendor/k8s.io/apimachinery/pkg/conversion/queryparams/BUILD
  vendor/k8s.io/apimachinery/pkg/fields/BUILD
  vendor/k8s.io/apimachinery/pkg/labels/BUILD
  vendor/k8s.io/apimachinery/pkg/runtime/BUILD
  vendor/k8s.io/apimachinery/pkg/runtime/schema/BUILD
  vendor/k8s.io/apimachinery/pkg/selection/BUILD
  vendor/k8s.io/apimachinery/pkg/types/BUILD
  vendor/k8s.io/apimachinery/pkg/util/clock/BUILD
  vendor/k8s.io/apimachinery/pkg/util/errors/BUILD
  vendor/k8s.io/apimachinery/pkg/util/intstr/BUILD
  vendor/k8s.io/apimachinery/pkg/util/json/BUILD
  vendor/k8s.io/apimachinery/pkg/util/net/BUILD
  vendor/k8s.io/apimachinery/pkg/util/runtime/BUILD
  vendor/k8s.io/apimachinery/pkg/util/validation/BUILD
  vendor/k8s.io/apimachinery/pkg/util/validation/field/BUILD
  vendor/k8s.io/apimachinery/pkg/util/wait/BUILD
  vendor/k8s.io/apimachinery/pkg/util/yaml/BUILD
  vendor/k8s.io/apimachinery/pkg/watch/BUILD
  vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/BUILD
  vendor/k8s.io/apiserver/pkg/util/flag/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#6774 Update kubernetes_e2e.py to fix typo
  scenarios/kubernetes_e2e.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6813 Adding a ci job to run kubemci ingress conformance tests
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6818 Revert "Revert "Enable PodPriority feature gate for GCE 2k-node performance test""
  jobs/env/ci-kubernetes-e2e-gce-large-performance.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6814 support gsed in prune-libraries
  hack/prune-libraries.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#6816 Collect cri-containerd-monitor log.
  jobs/env/ci-cri-containerd-e2e-gce.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6823 Add cri-containerd daemon log support.
  jobs/env/ci-cri-containerd-e2e-gce.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6825 Setting repo flag for kubemci push job
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6557 Add Jenkins cert-based auth in prow
  experiment/manual-trigger/manual-trigger.go
  prow/cmd/jenkins-operator/main.go
  prow/jenkins/jenkins.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6828 Updating args to pass the args to make instead of execute.py
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6827 support darwin in prow/bump.sh, ship it
  prow/bump.sh
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#6830 revert prow bump
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#6832 fix deck cookie mount and rebump prow
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#6831 Added new job to run ip-alias tests in ipvs mode
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6837 gcloud auth before push to gcr.io
  images/kubemci/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#6839 switch back to gcloud docker -- push
  images/kubemci/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#6838 Fix log links does not behave properly
  prow/cmd/deck/static/script.js
  prow/cmd/deck/static/style.css
Labels: approved, cncf-cla: yes, lgtm, size/M

#6833 fix github secret loading
  prow/bump.sh
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/cmd/deck/main.go
  prow/config/BUILD.bazel
  prow/config/githuboauth.go
  prow/config/githuboauth_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#6843 Add perfdash tags for benchmark support.
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6844 Remove notifications to myself.
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6845 Use streaming mode of ginkgo.
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6792 Turning on PR testing for kube-deploy
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6842 Fixes Deck table is not responsive on mobile
  prow/cmd/deck/static/command-help.html
  prow/cmd/deck/static/index.html
  prow/cmd/deck/static/plugins.html
  prow/cmd/deck/static/style.css
  prow/cmd/deck/static/tide.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#6848 Fixes bugs from Command Help that does not return plugins if there is no plugin for org/repo
  prow/cmd/deck/static/command-help-script.js
  prow/cmd/deck/static/plugins-script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#6849 bump prow to v20180215-1281b60f7
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S

#6824 clean up config test
  jobs/config_test.py
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#6846 Abort on timeout, to get stack traces.
  kubetest/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6855 Updating kubemci-image-push job to push latest image as well
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6821 Switch k/k to use the needs-rebase external plugin instead of the munger.
  mungegithub/misc-mungers/deployment/kubernetes/configmap.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6850 create DefaultFieldsFormatter and inject component into all prow messages
  experiment/nursery/BUILD.bazel
  experiment/nursery/main.go
  prow/BUILD.bazel
  prow/cmd/deck/BUILD.bazel
  prow/cmd/deck/main.go
  prow/cmd/hook/BUILD.bazel
  prow/cmd/hook/main.go
  prow/cmd/horologium/BUILD.bazel
  prow/cmd/horologium/main.go
  prow/cmd/jenkins-operator/BUILD.bazel
  prow/cmd/jenkins-operator/main.go
  prow/cmd/plank/BUILD.bazel
  prow/cmd/plank/main.go
  prow/cmd/sinker/BUILD.bazel
  prow/cmd/sinker/main.go
  prow/cmd/splice/BUILD.bazel
  prow/cmd/splice/main.go
  prow/cmd/tide/BUILD.bazel
  prow/cmd/tide/main.go
  prow/cmd/tot/BUILD.bazel
  prow/cmd/tot/main.go
  prow/logrusutil/BUILD.bazel
  prow/logrusutil/logrusutil.go
  prow/tide/tide.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#6851 For docs repo, no self approve, no issue required.
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6861 Trim all whitespace from `gcloud container get-server-config`
  kubetest/util.go
Labels: approved, area/kubetest, cncf-cla: yes, lgtm, size/XS

#6216 Add a parser for e2e test build-log.txt
  experiment/parse_build_log.py
  hack/pylint_bin.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#6863 Revert "Use streaming mode of ginkgo."
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6864 List all kubemark nodes before starting tests
  kubetest/e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6853 Separate build ID from ProwJob ID for Jenkins jobs
  experiment/manual-trigger/manual-trigger.go
  prow/README.md
  prow/cmd/jenkins-operator/main.go
  prow/jenkins/BUILD.bazel
  prow/jenkins/controller.go
  prow/jenkins/controller_test.go
  prow/jenkins/jenkins.go
  prow/kube/prowjob.go
  prow/pjutil/jobspec.go
  prow/pjutil/jobspec_test.go
  prow/pjutil/pjutil.go
  prow/pjutil/pjutil_test.go
  prow/plank/controller.go
  prow/plank/controller_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#6817 Set docker in docker to enable build during e2e setup.
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6854 Fix minor whoopsies in clonerefs/initupload
  prow/cmd/clonerefs/main.go
  prow/cmd/initupload/main.go
  prow/pod-utils/clone/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6803 Increase timeouts for autoscaling tests
  experiment/test_config.yaml
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6759 Add support for running hack/local-up-cluster.sh
  kubetest/BUILD.bazel
  kubetest/dump.go
  kubetest/kubernetes.go
  kubetest/local.go
  kubetest/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6867 Test option validation in clonerefs
  prow/cmd/clonerefs/BUILD.bazel
  prow/cmd/clonerefs/main.go
  prow/cmd/clonerefs/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6868 Refactor option validation in config entrypoint
  prow/cmd/config/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6859 move bazel cache rc creation into images
  experiment/bump_e2e_image.sh
  images/bootstrap/Dockerfile
  images/bootstrap/create_bazel_cache_rcs.sh
  images/bootstrap/runner
  images/kubekins-e2e/Dockerfile
  images/kubekins-e2e/Makefile
  prow/config.yaml
  scenarios/kubernetes_bazel.py
Labels: approved, area/bazel, area/images, area/jobs, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#6869 Test option validation in deck entrypoint
  prow/cmd/deck/main.go
  prow/cmd/deck/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6870 Fix check for the SSH key for the project being set up.
  kubetest/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6872 Test option validation for hook
  prow/cmd/hook/main.go
  prow/cmd/hook/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6871 Bump kubetest + kubekins-e2e
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  jobs/config.json
  prow/config.yaml
  scenarios/kubernetes_e2e.py
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6874 Refactor option validation in horologium
  prow/cmd/horologium/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6873 more image cleanup, move test-infra to bazel 0.10.1
  experiment/bump_e2e_image.sh
  images/bootstrap/Dockerfile
  images/bootstrap/runner
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6878 Test option validation for mkpj entrypoint
  prow/cmd/mkpj/BUILD.bazel
  prow/cmd/mkpj/main.go
  prow/cmd/mkpj/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6876 Test option validation for initupload
  prow/cmd/initupload/main.go
  prow/cmd/initupload/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6877 Test option validation for jenkins-operator
  prow/cmd/jenkins-operator/BUILD.bazel
  prow/cmd/jenkins-operator/main.go
  prow/cmd/jenkins-operator/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6875 clean up docker mode in e2e scenario
  experiment/bump_e2e_image.sh
  scenarios/kubernetes_e2e.py
  scenarios/kubernetes_e2e_test.py
Labels: approved, area/scenarios, cncf-cla: yes, lgtm, size/L

#6879 move/rename experiment/nursery to greenhouse, document, enable for test-infra
  BUILD.bazel
  experiment/BUILD.bazel
  experiment/nursery/README.md
  greenhouse/BUILD.bazel
  greenhouse/README.md
  greenhouse/deployment.yaml
  greenhouse/diskcache/BUILD.bazel
  greenhouse/diskcache/cache.go
  greenhouse/diskcache/cache_test.go
  greenhouse/diskutil/BUILD.bazel
  greenhouse/diskutil/diskutil.go
  greenhouse/main.go
  greenhouse/service.yaml
  prow/config.yaml
Labels: approved, area/bazel, area/jobs, cncf-cla: yes, lgtm, size/M

#6882 remove pull-kubernetes-e2e-kubeadm-gce-canary
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/L

#6881 e2e conformance test against local cluster
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6885 Checkout sources for ci-kubernetes-local-e2e
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6884 fix --extract=gke
  kubetest/extract_k8s.go
Labels: approved, area/kubetest, cncf-cla: yes, lgtm, priority/failing-test, size/S, ¯\_(ツ)_/¯

#6887 Oops! fix typo
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#6888 Bump e2e images
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  prow/config.yaml
Labels: approved, area/images, cncf-cla: yes, do-not-merge/hold, lgtm, size/XXL

#6889 Cleanup image bumping
  experiment/bump_e2e_image.sh
  images/kubekins-e2e/Dockerfile
  images/kubekins-e2e/Makefile
  prow/bump.sh
Labels: approved, area/images, cncf-cla: yes, lgtm, size/M

#6895 Increase #real-nodes for kubemark-5000
  jobs/env/ci-kubernetes-kubemark-gce-scale.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6896 Disable PodPriority feature gate for GCE 2k-node performance test
  jobs/env/ci-kubernetes-e2e-gce-large-performance.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6897 Decrease testgrid column recency for large-scale jobs
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6901 Add job for testing autoscaler on regional clusters
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6891 Enable DIND for ci-kubernetes-local-e2e
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6905 Run slow tests in ipvs mode.
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6894 fix(*): fix nil point dereference when do request return error
  prow/github/client.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6822 Remove showAPIType option from apicoverage
  experiment/coverage/apicoverage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6907 Bump kubernetes-anywhere version for kubeadm to include k-a PR #514
  images/kubeadm/runner
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6892 Adjust for new location of kubectl.sh and local-up-cluster.sh scripts in CI
  kubetest/extract_k8s.go
  kubetest/local.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6913 Bump kubekins to v20180220-5b25c840d
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6914 fix kubemark canary
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#6915 create bazel-scratch-dir preset
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#6902 Add prow job to test kubernetes-sig-testing/frameworks
  jobs/config.json
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/M

#6916 add job-state icons back to prow status
  prow/cmd/deck/static/.gitignore
  prow/cmd/deck/static/script.js
  prow/cmd/deck/static/style.css
Labels: approved, cncf-cla: yes, lgtm, size/M

#6657 Revert "Support /unhold (totally a word) as an alias for /hold cancel."
  prow/plugins/hold/hold.go
  prow/plugins/hold/hold_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6920 create kubekins-e2e 1.10
  experiment/bump_e2e_image.sh
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  images/kubekins-e2e/Makefile
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6910 Use Prow to run k8s-tpu-operator presumit checks
  jobs/config.json
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6917 Avoid chdir for --extract-source
  kubetest/local.go
  kubetest/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6922 add ssh keys for tpu repo
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#6921 Create kubekins-test for 1.10 branch
  images/kubekins-test/Dockerfile-1.10
  images/kubekins-test/Dockerfile-1.4
  images/kubekins-test/Dockerfile-1.6
  scenarios/kubernetes_verify.py
Labels: approved, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#6898 Add a gcsupload utility binary and image
  prow/BUILD.bazel
  prow/Makefile
  prow/cmd/gcsupload/BUILD.bazel
  prow/cmd/gcsupload/Dockerfile
  prow/cmd/gcsupload/OWNERS
  prow/cmd/gcsupload/main.go
  prow/cmd/initupload/BUILD.bazel
  prow/cmd/initupload/main.go
  prow/cmd/initupload/main_test.go
  prow/pod-utils/clone/clone.go
  prow/pod-utils/gcs/BUILD.bazel
  prow/pod-utils/gcs/options.go
  prow/pod-utils/gcs/options_test.go
  prow/pod-utils/gcs/target.go
  prow/pod-utils/gcs/target_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#6923 update gcloud container property name
  kubetest/gke.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6928 make port presubmit slightly less dumb
  prow/config.yaml
  prow/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#6926 add prometheus metrics to greenhouse
  greenhouse/BUILD.bazel
  greenhouse/README.md
  greenhouse/deployment.yaml
  greenhouse/diskcache/cache.go
  greenhouse/diskutil/diskutil.go
  greenhouse/main.go
  greenhouse/metrics-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6927 Support running k8s-tpu-operator tests in docker mode
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6929 add bazel-cache metrics to velodrome
  velodrome/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#6931 improve greenhouse README.md
  greenhouse/README.md
Labels: approved, area/bazel, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#6925 Disable initializer test for 1.7 -> 1.8 gke master upgrade test
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6933 switch aborted job icon
  prow/cmd/deck/static/script.js
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#6918 Remove MountPropagation from alpha tests
  experiment/test_config.yaml
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#6934 Enable golint and trigger plugins for kubernetes-sig-testing/frameworks
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6937 Minor bugfixes for pod utilities
  prow/cmd/initupload/main.go
  prow/pod-utils/clone/format.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/XS
