Repository kubernetes/test-infra, pull requests merged in 2018-03, with the labels that each got.

#7062 use go 1.10 in kubekins-e2e:experimental, bump kubekins, swtich ci-cri-containerd-build
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  images/kubekins-e2e/Makefile
  prow/config.yaml
Labels: approved, area/images, area/jobs, cncf-cla: yes, lgtm, size/XXL

#7066 set --root for typecheck job
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XS

#7065 publish ci/latest-bazel builds
  prow/config.yaml
  scenarios/kubernetes_bazel.py
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#7025 Make OwnersClient directory blacklist configurable.
  prow/cmd/hook/BUILD.bazel
  prow/cmd/hook/main.go
  prow/config/config.go
  prow/repoowners/repoowners.go
  prow/repoowners/repoowners_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#7058 Introduce the entrypoint and sidecar containers
  Gopkg.lock
  prow/BUILD.bazel
  prow/Makefile
  prow/cmd/entrypoint/BUILD.bazel
  prow/cmd/entrypoint/Dockerfile
  prow/cmd/entrypoint/OWNERS
  prow/cmd/entrypoint/main.go
  prow/cmd/entrypoint/main_test.go
  prow/cmd/sidecar/BUILD.bazel
  prow/cmd/sidecar/Dockerfile
  prow/cmd/sidecar/OWNERS
  prow/cmd/sidecar/main.go
  prow/pod-utils/wrapper/BUILD.bazel
  prow/pod-utils/wrapper/OWNERS
  prow/pod-utils/wrapper/doc.go
  prow/pod-utils/wrapper/options.go
  prow/pod-utils/wrapper/options_test.go
  vendor/BUILD.bazel
  vendor/github.com/fsnotify/fsnotify/.editorconfig
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/BUILD.bazel
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: approved, area/prow, cncf-cla: yes, kind/feature, lgtm, size/XXL

#7071 sig-autoscaling VPA actuation e2e tests.
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7074 start reporting typecheck
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/S

#7061 make push-build.sh path configurable
  scenarios/kubernetes_build.py
Labels: approved, area/scenarios, cncf-cla: yes, lgtm, size/XS

#7000 Re-enable audit logging in scale tests
  jobs/env/ci-kubernetes-e2e-gce-large-correctness.env
  jobs/env/ci-kubernetes-e2e-gce-scale-correctness.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7069 Enable ALLOW_PRIVILEGED for ci-kubernetes-local-e2e job
  kubetest/local.go
Labels: approved, area/kubetest, cncf-cla: yes, lgtm, size/XS

#7067 Split autoscaling e2e jobs and organize dashboard tabs.
  jobs/config.json
  jobs/config_test.py
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7076 Setup blunderbuss and tide for Kubeflow
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6982 [prow] milestone maintainers can set milestone
  prow/README.md
  prow/github/client.go
  prow/github/client_test.go
  prow/github/fakegithub/fakegithub.go
  prow/github/types.go
  prow/plugins.yaml
  prow/plugins/BUILD.bazel
  prow/plugins/milestone/BUILD.bazel
  prow/plugins/milestone/milestone.go
  prow/plugins/milestone/milestone_test.go
  prow/plugins/milestonestatus/milestonestatus.go
  prow/plugins/plugins.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#7075 Add README.md of apicoverage tool
  experiment/coverage/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7078 Security repo: disable bazel remote cache
  maintenance/fixconfig/main.go
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/S

#7079 Add a success message to GCS upload code
  prow/pod-utils/gcs/options.go
  prow/pod-utils/gcs/upload.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/XS

#7082 add missing ginkgo skips to 1.7-1.8 upgrade
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7085 format unix time in deck
  prow/cmd/deck/jobs.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/XS

#7086 fix timestamps parsing for prow status
  prow/cmd/deck/static/script.js
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S

#7088 flip timestamp and age hover
  prow/cmd/deck/static/script.js
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#7090 bikeshed the timestamp format to something shorter
  prow/cmd/deck/static/script.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7089 Configure Deck to refresh tide data every 1 second (was 10s).
  prow/config.yaml
Labels: approved, area/prow, cncf-cla: yes, kind/velocity-improvement, lgtm, size/XS

#7084 bump prow to v20180302-0064877cc
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S

#7092 use make verify WHAT=typecheck
  jobs/config.json
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XS

#7083 Fix broken milestone munger
  mungegithub/github/github.go
  mungegithub/mungers/milestone-maintainer.go
  mungegithub/mungers/milestone-maintainer_test.go
Labels: approved, area/mungegithub, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#7094 append gs:// to gcs path
  scenarios/kubernetes_build.py
Labels: approved, area/scenarios, area/so-crazy-it-just-might-work, cncf-cla: yes, lgtm, ¯\_(ツ)_/¯

#7095 install bc in kubekins-e2e and bump images
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  images/kubekins-e2e/Dockerfile
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL, ¯\_(ツ)_/¯

#7068 initupload pushes latest-build.txt for every job
  gubernator/README.md
  prow/pod-utils/gcs/options.go
  prow/pod-utils/gcs/target.go
  prow/pod-utils/gcs/target_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#7099 Enable milestone plugin for the Kubernetes org.
  prow/cluster/hook_deployment.yaml
  prow/cluster/starter.yaml
  prow/hook/BUILD.bazel
  prow/hook/plugins.go
  prow/plugins.yaml
  prow/plugins/plugins.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6815 Reduce repetitive code in trigger plugin and fix bug with branch sharded jobs.
  prow/plugins/trigger/ic.go
  prow/plugins/trigger/pr.go
  prow/plugins/trigger/trigger.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/L, ¯\_(ツ)_/¯

#7105 Update gazelle to latest to fix vendoring issue
  hack/update-bazel.sh
  hack/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7100 Moving kops validation tests out of travis
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7103 Trim down time display to hour:min:second
  prow/cmd/deck/static/script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#7104 Make the typecheck job put its artifacts in the right place.
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7108 Fix typecheck to output to _artifacts/ instead of artifacts/
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#7109 bump deck to v20180302-949b16f57
  prow/cluster/deck_deployment.yaml
  prow/cluster/starter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7102 Fix SetMilestone Github client function.
  prow/cluster/hook_deployment.yaml
  prow/cluster/starter.yaml
  prow/github/client.go
  prow/github/client_test.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/S

#7112 Fix tide serving invalid JSON.
  prow/tide/tide.go
  prow/tide/tide_test.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/S

#7111 add kops-bazel jobs
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/M

#7113 report kops presubmits
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XS

#7116 Make Gubernator track milestones for the PR dashboard.
  gubernator/github/classifier.py
  gubernator/github/classifier_test.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7117 make ci-kubernetes-e2e-kubeadm-gce independent of bazel-build scheduling
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7115 update rules-docker, and add a python base image
  WORKSPACE
Labels: approved, area/bazel, cncf-cla: yes, lgtm, size/S

#7118 update planter to point to bazel 0.11
  planter/Makefile
  planter/planter.sh
Labels: approved, area/planter, cncf-cla: yes, lgtm, size/XS

#7120 Only run milestone plugins on k/k
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, sig/testing, size/XS

#6241 Add front-end dashboard for log tracing
  experiment/tracer/static/dashboard.html
  experiment/tracer/static/script.js
  experiment/tracer/static/style.css
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#6991 Add pull-kubernetes-local-e2e
  jobs/config.json
  jobs/config_test.py
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7131 Make large scale tests manual temporarily
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7124 Integrate frontend in the log tracer
  experiment/tracer/Dockerfile
  experiment/tracer/main.go
  experiment/tracer/static/index.html
  experiment/tracer/static/script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#7110 Trigger plugin touch ups.
  prow/plugins/trigger/ic.go
  prow/plugins/trigger/trigger.go
Labels: approved, area/prow, cncf-cla: yes, kind/documentation, lgtm, size/M

#6935 Fix running multiple pull jobs for federation
  jobs/config.json
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/multicluster, size/XS

#7129 No need to --stage builds from pull-kubernetes-local-e2e
  jobs/config.json
  jobs/config_test.py
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#7135 Don't show BeforeSuite in the dashboard to avoid spurious alerts.
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7133 Ensure that GCS alias files contain full GCS paths
  prow/pod-utils/gcs/options.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/XS

#7127 It is UTF-8 not utf8
  hack/coalesce.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7138 Revert "Make large scale tests manual temporarily"
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7134 Bump Tide to v20180305-a0d0c9688.
  prow/cluster/tide_deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7139 fix kubeadm ci path logic
  kubetest/anywhere.go
  kubetest/anywhere_test.go
  scenarios/kubernetes_e2e.py
  scenarios/kubernetes_e2e_test.py
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#7143 Istio Test Command in Gubernator to Avoid `hack/e2e.go`
  gubernator/filters.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7141 Update cri-containerd test config to test plugin mode.
  jobs/config.json
  jobs/env/ci-cri-containerd-e2e-gce.env
Labels: approved, cncf-cla: yes, lgtm, size/S

#7145 Bump kubekins for kubeadm
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7144 Add milestone filtering to PR dashboard.
  gubernator/Makefile
  gubernator/github/classifier.py
  gubernator/static/style.css
  gubernator/templates/pr_dashboard.html
  gubernator/view_pr.py
  gubernator/view_pr_test.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#7148 let 1.10 kubelet job run more often
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7147 Refactor ci jobs
  jobs/config.json
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XXL

#7072 tot uses prow config to determine fallback GCS path
  prow/cmd/tot/BUILD.bazel
  prow/cmd/tot/fallbackcheck/BUILD.bazel
  prow/cmd/tot/fallbackcheck/main.go
  prow/cmd/tot/main.go
  prow/cmd/tot/main_test.go
  prow/pjutil/jobspec.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#7150 GKE Regional Clusters upgrade tests
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7093 prow: fuzzy search should not include jobs that do not belong to a repo
  prow/cmd/deck/static/fuzzy-search.js
  prow/cmd/deck/static/index.html
  prow/cmd/deck/static/script.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#7151 Add validation for repo sync config in clonerefs
  prow/cmd/clonerefs/BUILD.bazel
  prow/cmd/clonerefs/main.go
  prow/cmd/clonerefs/main_test.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/M

#7155 Use full containerd name.
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#7101 Remove jenkins section, add config_sort reminder in README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S, ¯\_(ツ)_/¯

#7160 make kubeadm ci jobs run
  jobs/config.json
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#7162 fix ci bazel bulid 1-7 and 1-8
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#7163 Set hairpin mode to hairpin-veth for ipvs tests
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7166 Fix Regional Clusters tests
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7167 Introduce a test job for Core DNS.
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7154 Add a timeout to the entrypoint wrapper
  prow/cmd/entrypoint/main.go
Labels: approved, area/prow, cncf-cla: yes, kind/feature, lgtm, size/S

#7168 Add optional presubmits for scale-testing on GCE-100/500/2000 clusters
  jobs/config.json
  jobs/config_test.py
  jobs/env/ci-kubernetes-e2e-gce-big-performance.env
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#7136 Fix milestone plugin comment formatting.
  prow/plugins/milestone/milestone.go
  prow/plugins/milestone/milestone_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#7158 make getLatestGKEVersion accept no zones
  kubetest/extract_k8s.go
  kubetest/extract_test.go
  kubetest/gke.go
  kubetest/main.go
  kubetest/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7172 bump kubekins for regional cluster upgrade suites
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7170 Make bootstrap keep git ssh config for the duration of testing.
  jenkins/bootstrap.py
  jenkins/bootstrap_test.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#7122 prow: PR Status with a new feature
  prow/BUILD.bazel
  prow/cmd/deck/BUILD.bazel
  prow/cmd/deck/main.go
  prow/cmd/deck/runlocal
  prow/cmd/deck/static/.gitignore
  prow/cmd/deck/static/pr-script.js
  prow/cmd/deck/static/pr.html
  prow/cmd/deck/static/style.css
  prow/prstatus/BUILD.bazel
  prow/prstatus/prstatus.go
  prow/prstatus/prstatus_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#7169 Fix some stuff in core dns e2e test
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7171 ci job refactoring
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XXL

#7176 don't enforce --gcp-zone for gke-latest tests
  kubetest/extract_k8s.go
Labels: approved, area/kubetest, cncf-cla: yes, lgtm, size/XS

#7177 Include Istio Daily Releases to Testgrid
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7070 PVCProtection feature was renamed to StorageObjectInUseProtection and was brought to beta
  experiment/test_config.yaml
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#7114 removing singapore region from tests
  kubetest/kops.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7182 Use bazel build mode for scalability presubmits
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7030 Add e2e-node test job for alpha features
  jobs/config.json
  jobs/config_test.py
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, sig/node, size/M

#7181 No more notifications for kargakis
  CODEOWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7186 setup periodic bazel-build for 1.10 and 1.9
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#7189 Bump Prow to v20180308-43ea85da7
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7188 Add framework for testing with image families on GKE
  kubetest/gke.go
  kubetest/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7190 Fix gcs_prefix for istio daily jobs on testgrid
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7132 Share story about running node e2e tests on RHEL in AWS
  docs/tests/node-e2e-ci.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7191 add fortio to istio repos
  velodrome/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7175 prow: adds scroll top button to Prow Status
  prow/cmd/deck/static/index.html
  prow/cmd/deck/static/script.js
  prow/cmd/deck/static/style.css
Labels: approved, cncf-cla: yes, lgtm, size/M

#7196 support extract from arbitrary gcs filepointer
  kubetest/extract_k8s.go
  kubetest/extract_test.go
Labels: approved, area/kubetest, cncf-cla: yes, lgtm, size/S

#7194 Greenhouse: switch to pd-ssd, drop --remount
  greenhouse/README.md
  greenhouse/deployment.yaml
  greenhouse/diskutil/diskutil.go
  greenhouse/gce-storage.yaml
  greenhouse/main.go
  greenhouse/metrics-service.yaml
  greenhouse/service.yaml
Labels: approved, area/greenhouse, cncf-cla: yes, lgtm, size/L

#7165 Update fuzzy search scoring function to be more accurate
  prow/cmd/deck/static/fuzzy-search.js
  prow/cmd/deck/static/script.js
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#7199 fix misspelling of Kubernetes
  prow/prstatus/prstatus_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7201 Add QA jobs for COS milestone 66
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#7202 eliminate a lot of unnecessary local SSD usage
  maintenance/fixconfig/main.go
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/L

#7200 Create new labels to identify issues as close candidates
  label_sync/labels.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/XS

#7193 Add a test for V100 against the GKE staging endpoint.
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7207 Specify num-nodes through gke-shape.
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7209 fallbackcheck ignores non-existent GCS buckets
  prow/cmd/tot/fallbackcheck/README.md
  prow/cmd/tot/fallbackcheck/main.go
  prow/pod-utils/gcs/target.go
  prow/pod-utils/gcs/target_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7218 Fix image family mismatch in QA jobs of cos milestone 66
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7205 flip on the bazel remote cache for more presubmits
  maintenance/fixconfig/main.go
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7217 enable dashboard addon in failing GKE tests
  jobs/config.json
Labels: approved, area/jobs, cncf-cla: yes, lgtm, priority/failing-test, size/XS

#7204 prow: notify users if LGTM label is removed due to new pull request
  prow/plugins/lgtm/BUILD.bazel
  prow/plugins/lgtm/lgtm.go
  prow/plugins/lgtm/lgtm_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#7216 prow: prow status shows job counts
  prow/cmd/deck/static/index.html
  prow/cmd/deck/static/script.js
  prow/cmd/deck/static/style.css
Labels: approved, cncf-cla: yes, lgtm, size/L

#7215 Improve Kubernetes client logging
  prow/kube/client.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/XS

#7224 Don't ignore errors from closing readers/writers for GCS
  prow/BUILD.bazel
  prow/errorutil/BUILD.bazel
  prow/errorutil/aggregate.go
  prow/errorutil/doc.go
  prow/pod-utils/gcs/BUILD.bazel
  prow/pod-utils/gcs/upload.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/L

#7198 prow/pr_status: get user login after exchange the token
  prow/cmd/deck/main.go
  prow/githuboauth/BUILD.bazel
  prow/githuboauth/githuboauth.go
  prow/githuboauth/githuboauth_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#7219 Enable dumping cluster logs by default for kubernetes-anywhere jobs
  jobs/config.json
  kubetest/anywhere.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7214 Upload the ProwJob spec from initupload
  prow/cmd/initupload/main.go
Labels: approved, area/prow, cncf-cla: yes, kind/feature, lgtm, size/XS

#7226 bump kubetest to pick up log dump changes
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7211 Leave detached HEAD state in clonerefs
  prow/pod-utils/clone/clone.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/XS

#7212 fix-typo-in-submit-queue.go
  mungegithub/mungers/submit-queue.go
Labels: approved, cncf-cla: yes, lgtm, retest-not-required, size/XS

#7210 Revert "Merge pull request #5403 from stevekuznetsov/skuznets/tighter-spec-validation"
  prow/config/config.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#7228 Follow kubernetes-sig-testing/frameworks repo transfer
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7208 Try running dev ubuntu image validation on GKE
  experiment/test_config.yaml
  jobs/config.json
  jobs/config_test.py
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7231 enable istio addon for istio gke e2e test
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7232 bump deck to v20180312-ab4b42e25
  prow/cluster/deck_deployment.yaml
  prow/cluster/starter.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/XS

#7197 Make tide set a more useful status.
  prow/config/tide.go
  prow/tide/tide.go
  prow/tide/tide_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7237 Enable Secure, HttpOnly, Path and Expires for some cookies in PR Status
  prow/githuboauth/githuboauth.go
  prow/prstatus/prstatus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7241 Allow approve label and merge for scheduling_poseidon
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7239 Run summary api test.
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7248 Name the entrypoint package correctly
  prow/cmd/entrypoint/BUILD.bazel
  prow/cmd/entrypoint/main.go
  prow/cmd/entrypoint/main_test.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/S, ¯\_(ツ)_/¯

#7249 fix http redirect bug in deck
  prow/cmd/deck/main.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/XS, ¯\_(ツ)_/¯

#7250 prow/pr_status: on enter, make the search instead of new line
  prow/cmd/deck/static/pr-script.js
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S

#7253 Do not comment when lgtm is not found in PRs
  prow/plugins/lgtm/lgtm.go
  prow/plugins/lgtm/lgtm_test.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/M

#7243 Update COS versions to latest stable/beta/dev
  experiment/test_config.yaml
  jobs/config.json
  jobs/e2e_node/benchmark-config.yaml
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7257 add needs-rebase image to prow docker bundle
  prow/BUILD.bazel
  prow/cluster/BUILD.bazel
  prow/external-plugins/needs-rebase/BUILD.bazel
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S

#7259 set pure=on for needs-rebase
  prow/external-plugins/needs-rebase/BUILD.bazel
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#7260 use staging gcloud + set command group to be alpha
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7252 bump prow to v20180313-8a0eb795d
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7246 Rename `cri-containerd` to `cri`.
  jobs/config.json
  jobs/env/ci-cri-containerd-e2e-gce.env
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7261 Make prow's config agent poll for changes every second.
  prow/config/agent.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6835 Gerrit fetcher in prow
  Gopkg.lock
  prow/BUILD.bazel
  prow/cmd/gerrit/BUILD.bazel
  prow/cmd/gerrit/main.go
  prow/cmd/gerrit/third_party/git-cookie-authdaemon
  prow/config/config.go
  prow/gerrit/BUILD.bazel
  prow/gerrit/gerrit.go
  prow/gerrit/gerrit_test.go
  vendor/BUILD.bazel
  vendor/github.com/andygrunwald/go-gerrit/.gitignore
  vendor/github.com/andygrunwald/go-gerrit/.travis.yml
  vendor/github.com/andygrunwald/go-gerrit/BUILD.bazel
  vendor/github.com/andygrunwald/go-gerrit/CHANGELOG.md
  vendor/github.com/andygrunwald/go-gerrit/LICENSE
  vendor/github.com/andygrunwald/go-gerrit/Makefile
  vendor/github.com/andygrunwald/go-gerrit/README.md
  vendor/github.com/andygrunwald/go-gerrit/access.go
  vendor/github.com/andygrunwald/go-gerrit/accounts.go
  vendor/github.com/andygrunwald/go-gerrit/authentication.go
  vendor/github.com/andygrunwald/go-gerrit/changes.go
  vendor/github.com/andygrunwald/go-gerrit/changes_edit.go
  vendor/github.com/andygrunwald/go-gerrit/changes_reviewer.go
  vendor/github.com/andygrunwald/go-gerrit/changes_revision.go
  vendor/github.com/andygrunwald/go-gerrit/config.go
  vendor/github.com/andygrunwald/go-gerrit/doc.go
  vendor/github.com/andygrunwald/go-gerrit/events.go
  vendor/github.com/andygrunwald/go-gerrit/gerrit.go
  vendor/github.com/andygrunwald/go-gerrit/gometalinter.json
  vendor/github.com/andygrunwald/go-gerrit/groups.go
  vendor/github.com/andygrunwald/go-gerrit/groups_include.go
  vendor/github.com/andygrunwald/go-gerrit/groups_member.go
  vendor/github.com/andygrunwald/go-gerrit/plugins.go
  vendor/github.com/andygrunwald/go-gerrit/projects.go
  vendor/github.com/andygrunwald/go-gerrit/projects_branch.go
  vendor/github.com/andygrunwald/go-gerrit/projects_childproject.go
  vendor/github.com/andygrunwald/go-gerrit/projects_commit.go
  vendor/github.com/andygrunwald/go-gerrit/projects_dashboard.go
  vendor/github.com/andygrunwald/go-gerrit/projects_tag.go
  vendor/github.com/andygrunwald/go-gerrit/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7240 prow: improve job status bar
  prow/cmd/deck/static/index.html
  prow/cmd/deck/static/script.js
  prow/cmd/deck/static/style.css
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#7264 Use .Equal() to compare Time objects.
  prow/config/agent.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7247 Move the logic for getting the latest OS image from scenario to kubetest
  kubetest/main.go
  scenarios/kubernetes_e2e.py
  scenarios/kubernetes_e2e_test.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#7266 bump kubekins to v20180313-3e7524a90
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7268 add pr-kubemark canary job
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#7270 update gubernator ci jobs list to some current blocking jobs
  gubernator/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7271 add config.json entry for kubemark-canary job
  jobs/config.json
  jobs/config_test.py
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#7265 Adding gce-multizone flag in regional cluster upgrade tests
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
