Repository kubernetes/test-infra, pull requests merged in 2018-07, with the labels that each got.

#8518 Istio flakiness metrics by week
  metrics/README.md
  metrics/configs/istio-flakes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8529 switch pull-test-infra-lint to date-sha tagged image
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#8530 fix planter checks for set env
  planter/planter.sh
Labels: approved, area/planter, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#8528 Cleanup triggers section
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8535 Enable profiling for various components
  jobs/env/ci-kubernetes-e2e-scalability-common.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8534 Add conformance test results for Openstack and MS Azure
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8533 fix bazel cache rc script package version resolution and shellcheck lint
  images/bootstrap/create_bazel_cache_rcs.sh
Labels: approved, area/greenhouse, cncf-cla: yes, lgtm, size/S

#8504 genjobs improvements
  config/README.md
  config/jobs/kubernetes-security/generated-security-jobs.yaml
  config/jobs/kubernetes-security/genjobs.go
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/L

#8521 defer resolve podutil decoration
  prow/config/config.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#8539 Correct location of update-bazel.sh in verify-bazel.sh help message.
  hack/verify-bazel.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#8541 Bump timeout for gce-pd-csi-driver e2e test.
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8542 fix id -F does not exist on linux
  planter/planter.sh
Labels: approved, area/planter, cncf-cla: yes, lgtm, size/XS

#8546 remove deprecated gcloud config call
  kubetest/gke.go
Labels: approved, area/kubetest, cncf-cla: yes, lgtm, size/XS

#8545 retry service account activation instead of immediately failing
  jenkins/bootstrap.py
Labels: approved, area/bootstrap, cncf-cla: yes, lgtm, size/M

#8547 bump kubekins for istio addon test
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8548 Allow other packages in Prow to utilize JobAgent
  prow/BUILD.bazel
  prow/cmd/deck/BUILD.bazel
  prow/cmd/deck/main.go
  prow/deck/jobs/BUILD.bazel
  prow/deck/jobs/jobs.go
  prow/deck/jobs/jobs_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#8551 export plank.GitHubClient and use it consistently
  prow/cmd/plank/main.go
  prow/plank/controller.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S

#8554 Cleanup scalability tests configs
  jobs/config.json
  jobs/env/ci-kubernetes-e2e-gce-large-correctness.env
  jobs/env/ci-kubernetes-e2e-gci-gce-scalability-beta.env
  jobs/env/ci-kubernetes-e2e-gci-gce-scalability-stable.env
  jobs/env/ci-kubernetes-e2e-gci-gce-scalability.env
  jobs/env/ci-kubernetes-e2e-scalability-common.env
Labels: approved, cncf-cla: yes, lgtm, size/S

#8558 Prow: Use option structs instead of global flags
  prow/cmd/plank/main.go
  prow/cmd/sinker/main.go
  prow/cmd/splice/main.go
  prow/cmd/tide/main.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#8538 bump kubekins tag from config/jobs as well
  experiment/bump_e2e_image.sh
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#8540 debug bazelrc contents
  images/bootstrap/create_bazel_cache_rcs.sh
Labels: approved, area/bazel, cncf-cla: yes, lgtm, size/XS

#8543 defer all config validation logic
  prow/config/config.go
  prow/config/config_test.go
  prow/config/jobs_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#8560 Add ingress test job for release 1.2 branch
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8564 fix jobs dir in hack/update-config.sh
  hack/update-config.sh
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#8537 feat(needs-rebase): add Dockerfile and Makefile for
  prow/Makefile
  prow/external-plugins/needs-rebase/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#8565 fix gubernator url for gerrit
  prow/gerrit/gerrit.go
Labels: approved, area/prow, area/so-crazy-it-just-might-work, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#8431 prowjob attempt
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8562 temporarily switch bazel canaries to fixed image with bazel 0.15
  config/jobs/kubernetes-security/generated-security-jobs.yaml
  config/jobs/kubernetes/test-infra/test-infra-canaries.yaml
  prow/config.yaml
Labels: approved, area/bazel, cncf-cla: yes, lgtm, size/S

#8568 Istio testgrid new entry: cloud foundary test
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8570 strip internal url
  prow/gerrit/gerrit.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8573 Improve Triage UI, add "file bug" links.
  triage/index.html
  triage/interactive.js
  triage/model.js
  triage/render.js
  triage/style.css
Labels: approved, cncf-cla: yes, lgtm, size/L

#8571 Handle 404s in tot fallback better.
  prow/cmd/tot/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8572 Make https://prow.k8s.io/pr autologin (like Gubernator's /pr).
  prow/cmd/deck/static/github-login.html
  prow/cmd/deck/static/pr-script.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#8561 add gke-staging-beta jobs point to 1.11, also split out the staging config
  config/jobs/gke/gke-staging.yaml
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XL

#8556 Minor kubemark configs cleanup
  jobs/env/ci-kubernetes-e2e-kubemark-common.env
  jobs/env/ci-kubernetes-kubemark-gce-scale.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8575 Increase verbosity for 5k node tests
  jobs/config.json
  jobs/env/ci-kubernetes-e2e-gce-scale-correctness.env
  jobs/env/ci-kubernetes-e2e-gce-scale-performance.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8555 Enable advanced audit in kubemark-5000
  jobs/env/ci-kubernetes-kubemark-gce-scale.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8576 Enable kubelet profiling for scalability tests
  jobs/env/ci-kubernetes-e2e-scalability-common.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8578 Enable profiling of etcd in scalability tests
  jobs/env/ci-kubernetes-e2e-kubemark-common.env
  jobs/env/ci-kubernetes-e2e-scalability-common.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8553 Automate merges in kubernetes/publishing-bot
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8581 escape backslashes from ginkgo args
  config/jobs/gke/gke-staging.yaml
  config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/S

#8585 Increase qps limits for scalability tests
  jobs/env/ci-kubernetes-e2e-scalability-common.env
  jobs/env/ci-kubernetes-e2e-scalability-highspeed-common.env
Labels: approved, cncf-cla: yes, lgtm, size/S

#8586 escape the right way
  config/jobs/gke/gke-staging.yaml
  config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#8590 Fix scalability jobs in 1.10 and 1.9 releases
  jobs/env/ci-kubernetes-e2e-gci-gce-scalability-stable.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8592 Add hollow proxy test args
  jobs/env/ci-kubernetes-kubemark-gce-scale.env
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8593 Rename gce-large job clusters
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8589 Use logexporter for scalability jobs
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8583 Remove kubemark-5 jobs
  jobs/config.json
  jobs/config_test.py
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8569 don't panic ever when loading prow-config
  prow/config/config.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S

#8596 fix bump_e2e_image.sh
  experiment/bump_e2e_image.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8597 make bump_e2e_image.sh handle kubeadm in config/jobs
  experiment/bump_e2e_image.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#8550 Make Tide use the 'HeadRefs' field when possible.
  prow/tide/status.go
  prow/tide/tide.go
  prow/tide/tide_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#8598 correct sed for kubeadm images
  experiment/bump_e2e_image.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#8460 use kubectl from the lower layers in the kubeadm image
  config/jobs/gke/gke-staging.yaml
  config/jobs/kubernetes-security/generated-security-jobs.yaml
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL, ¯\_(ツ)_/¯

#8599 Add --fix* flags, remove bomb
  prow/cmd/peribolos/main.go
  prow/cmd/peribolos/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8580 Update branch managers post-1.11 release
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8600 Add RunAsGroup test in alpha test suite.
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8591 Add ToC generation to label_sync
  label_sync/labels.md
  label_sync/labels.md.tmpl
  label_sync/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8527 Trust repo collaborators unless disabled
  prow/ANNOUNCEMENTS.md
  prow/github/fakegithub/fakegithub.go
  prow/plugins.yaml
  prow/plugins/plugins.go
  prow/plugins/trigger/BUILD.bazel
  prow/plugins/trigger/ic.go
  prow/plugins/trigger/ic_test.go
  prow/plugins/trigger/pr.go
  prow/plugins/trigger/pr_test.go
  prow/plugins/trigger/trigger.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8601 Improve peribolos around child teams, uppercase, invitations
  prow/cmd/peribolos/main.go
  prow/cmd/peribolos/main_test.go
  prow/cmd/peribolos/test-config.yaml
  prow/github/client.go
  prow/github/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8604 Enable audit logs for performance tests
  jobs/config.json
  jobs/env/ci-kubernetes-e2e-gce-large-performance.env
  jobs/env/ci-kubernetes-e2e-gce-scale-performance.env
Labels: approved, cncf-cla: yes, lgtm, size/S

#8606 Create pull-rules-k8s-e2e presubmit
  prow/config.yaml
  testgrid/cmd/configurator/config_test.go
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8609 Move gke-regional scalability job to IP aliases
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8611 Bump timeout for gke-performance jobs & decrease for correctness job
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8615 bump prow to v20180709-7109caeb1
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#8608 Remove references to `kubernetes-pm`
  jobs/validOwners.json
Labels: approved, cncf-cla: yes, lgtm, sig/pm, size/XS

#8616 Enable bazel build for kubemark-canary
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8617 trust kubernetes org for kubernetes, kubernetes-incubator, kubernetes…
  prow/plugins.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/XS

#8607 Skip Feature:Volumes in alpha tests.
  experiment/test_config.yaml
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#8619 roll back tide to v20180627-ea5075d37
  prow/cluster/tide_deployment.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/XS

#8620 Add @apelisse as branch manager for server-side-apply
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7538 Make milestone maintainer team configurable per repo.
  label_sync/labels.md
  label_sync/labels.yaml
  prow/ANNOUNCEMENTS.md
  prow/github/fakegithub/fakegithub.go
  prow/plugins.yaml
  prow/plugins/milestone/BUILD.bazel
  prow/plugins/milestone/milestone.go
  prow/plugins/milestone/milestone_test.go
  prow/plugins/milestonestatus/BUILD.bazel
  prow/plugins/milestonestatus/milestonestatus.go
  prow/plugins/milestonestatus/milestonestatus_test.go
  prow/plugins/plugins.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#8624 bump gke upgrade jobs version to include 1.10-1.11 upgrades
  config/jobs/gke/gke-staging-gpu.yaml
  config/jobs/gke/gke-staging-upgrade.yaml
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XL

#8625 Bump hook for milestone config changes.
  prow/cluster/hook_deployment.yaml
  prow/cluster/starter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8626 fix --scenario flag
  config/jobs/gke/gke-staging-gpu.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#8623 add tests for scenario args
  config/tests/jobs/BUILD.bazel
  config/tests/jobs/jobs_test.go
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/L

#8630 Always trigger testing for PRs from trusted users
  prow/plugins/trigger/ic.go
  prow/plugins/trigger/ic_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8631 Update hook to v20180710-7b6ac39a1
  prow/cluster/hook_deployment.yaml
  prow/cluster/starter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8632 Increase stale time
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8633 Shorter perfdash tags for scalability jobs
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8636 remove the long gone e2e-runner
  images/kubekins-e2e/e2e-runner.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#8635 fix the gerrit url hack
  prow/gerrit/gerrit.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8641 Add unit tests to CI for pull-gcp-compute-persistent-disk-csi-driver
  config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/OWNERS
  config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8637 Add job to prevent issues in `k/features` from being marked with `lifecycle/frozen`
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, sig/pm, sig/testing, size/M

#8638 migrate kubeflow jobs to its own config subdir
  config/jobs/kubeflow/OWNERS
  config/jobs/kubeflow/kubeflow-periodics.yaml
  config/jobs/kubeflow/kubeflow-postsubmits.yaml
  config/jobs/kubeflow/kubeflow-presubmits.yaml
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XL

#8466 Allow multiple instance of a same job name
  prow/config/config.go
  prow/config/config_test.go
  prow/config/jobs.go
  prow/config/jobs_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8517 Split out test-infra config
  config/jobs/kubernetes/test-infra/janitors.yaml
  config/jobs/kubernetes/test-infra/test-infra-periodics.yaml
  config/jobs/kubernetes/test-infra/test-infra-postsubmits.yaml
  config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml
  jobs/config.json
  prow/config.yaml
  prow/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8654 Add pull unit and verify jobs to gcp-filestore-csi-driver repo
  config/jobs/kubernetes-sigs/gcp-filestore-csi-driver/OWNERS
  config/jobs/kubernetes-sigs/gcp-filestore-csi-driver/gcp-filestore-csi-driver-config.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8655 The actual image name is cos_containerd.
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8651 migrate cadvisor jobs to its own config file
  config/jobs/cadvisor/OWNERS
  config/jobs/cadvisor/cadvisor.yaml
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8658 Update azure lint test to check test
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8661 Move gce-scale jobs to us-east1-b
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8662 Disable advanced audit-logging in gce-scale-performance
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8660 initial setup and ci job for kubernetes-sigs/cluster-api-provider-openstack
  config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-presubmits.yaml
  prow/config.yaml
  prow/plugins.yaml
  testgrid/cmd/configurator/config_test.go
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8511 Fix (again) verify-owners
  prow/plugins/verify-owners/verify-owners.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8657 Validate prow labels, and don't hard-code prow.k8s.io
  Gopkg.lock
  prow/pjutil/BUILD.bazel
  prow/pjutil/pjutil.go
  prow/pjutil/pjutil_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#8666 prow: trigger: skip jobs whose parents are skipped
  prow/plugins/trigger/trigger.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/S

#8673 migrate some sig-node CI jobs
  config/jobs/kubernetes/sig-node/OWNERS
  config/jobs/kubernetes/sig-node/node-kubelet.yaml
  jobs/config.json
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XL

#8663 Set perfDashBuildsCount: 1000 for ci-kubernetes-e2e-gci-gce-scalability.
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8680 Reduce gce-100 perfdash range to half
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8681 Revert "Rename gce-large job clusters"
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8682 enable merge automation for k/release
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8683 Update sig-node test config approvers
  config/jobs/kubernetes/sig-node/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8674 migrate rules_k8s job to its own subdir
  config/jobs/bazelbuild/rules_k8s/OWNERS
  config/jobs/bazelbuild/rules_k8s/rules_k8s_config.yaml
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8684 Bump tide to latest, revert 2c1848d
  prow/cluster/tide_deployment.yaml
  prow/tide/status.go
  prow/tide/tide.go
  prow/tide/tide_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#8686 Retire GCI jobs and the project pool
  boskos/janitor/deployment.yaml
  boskos/metrics/deployment.yaml
  boskos/reaper/deployment.yaml
  boskos/resources.yaml
  jobs/config.json
  prow/config.yaml
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8687 Adding TEST_ETCD_VERSION=3.0.17 config in GPU downgrade test.
  jobs/config.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8559 Add required_reviewers on PRs
  prow/ANNOUNCEMENTS.md
  prow/plugins/approve/approve_test.go
  prow/plugins/blunderbuss/blunderbuss.go
  prow/plugins/blunderbuss/blunderbuss_test.go
  prow/plugins/lgtm/lgtm_test.go
  prow/repoowners/repoowners.go
  prow/repoowners/repoowners_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8689 Honor branding while serving favicon.ico
  prow/cmd/deck/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#8644 Display dialog when page is loaded with #plugin
  prow/cmd/deck/static/command-help-script.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8692 Specify a default code-search path for regression links.
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8693 allow overwrite gubernator path in unit test
  config/tests/jobs/jobs_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/S

#8694 Remove kube-deploy tests for the cluster api code.
  images/kube-deploy/Makefile
  jobs/config.json
  prow/config.yaml
  prow/plugins.yaml
  testgrid/cmd/configurator/config_test.go
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8695 Enable milestone plugin for k/test-infra
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8696 allow overwrite gcs bucket as well
  config/tests/jobs/jobs_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#8685 Make generated jobs generate to its own config file
  README.md
  config/jobs/kubernetes/generated/OWNERS
  config/jobs/kubernetes/generated/generated.yaml
  experiment/BUILD.bazel
  experiment/generate_tests.py
  jobs/config.json
  prow/config.yaml
Labels: approved, area/so-crazy-it-just-might-work, cncf-cla: yes, lgtm, size/XXL

#8697 Bump kubernetes-anywhere version
  images/kubeadm/runner
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8704 Bump timeout for nosnat job to 40m
  config/jobs/kubernetes/generated/generated.yaml
  experiment/test_config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8699 fix kubekins-e2e and experiment/bump_e2e_image.sh, bump e2e images
  config/jobs/cadvisor/cadvisor.yaml
  config/jobs/gke/gke-staging-gpu.yaml
  config/jobs/gke/gke-staging-upgrade.yaml
  config/jobs/gke/gke-staging.yaml
  config/jobs/kubernetes-security/generated-security-jobs.yaml
  config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-presubmits.yaml
  config/jobs/kubernetes/generated/generated.yaml
  config/jobs/kubernetes/sig-node/node-kubelet.yaml
  config/jobs/kubernetes/test-infra/test-infra-periodics.yaml
  config/jobs/kubernetes/test-infra/test-infra-postsubmits.yaml
  config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml
  experiment/bump_e2e_image.sh
  experiment/generate_tests.py
  experiment/test_config.yaml
  images/kubeadm/Dockerfile
  images/kubekins-e2e/Dockerfile
  prow/config.yaml
Labels: approved, area/images, area/jobs, cncf-cla: yes, lgtm, size/XXL

#8708 [prow/tide]: add k-sigs/kustomize to tide
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8711 add approve for kustomize repo
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8712 fix ginkgo focus escapes
  config/jobs/gke/gke-staging-gpu.yaml
  config/jobs/gke/gke-staging-upgrade.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8719 Fix containerd gke test.
  config/jobs/gke/containerd/gke-test-containerd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8723 prow: Update plugins.yaml documentation
  prow/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8718 move service-catalog prow config to specific directory
  config/jobs/kubernetes-incubator/service-catalog/OWNERS
  config/jobs/kubernetes-incubator/service-catalog/service-catalog-presubmits.yaml
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8715 tide documentation
  prow/README.md
  prow/cmd/tide/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8706 migrate charts to its own config file
  config/jobs/kubernetes/charts/OWNERS
  config/jobs/kubernetes/charts/charts.yaml
  jobs/config.json
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8727 make svccat do a squash merge
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8722 prow: kube-client: differentiate between GetLog and GetContainerLog
  prow/deck/jobs/jobs.go
  prow/deck/jobs/jobs_test.go
  prow/kube/client.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/S

#8729 correct configmap keys in getting_started.yaml
  prow/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8671 When the entrypoint receives SIGINT/SIGTERM, record an abort
  prow/entrypoint/run.go
  prow/sidecar/run.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#8714 Migrate rest of test-infra jobs and canary jobs
  config/jobs/kubernetes-security/generated-security-jobs.yaml
  config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml
  config/jobs/kubernetes/test-infra/test-infra-periodics.yaml
  jobs/config.json
  jobs/config_test.py
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/XXL

#8736 prow: pr status fixes
  prow/cmd/deck/static/pr-script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#8732 bump prow to v20180719-99bda6d00
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/starter.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/M

#8725 Updating charts config for move to helm GH org
  config/jobs/helm/charts/OWNERS
  config/jobs/helm/charts/charts.yaml
  config/jobs/kubernetes/charts/OWNERS
  prow/config.yaml
  prow/config/tide_test.go
  prow/plugins.yaml
  testgrid/cmd/configurator/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8739 Test required_reviewers with prow config
  CODEOWNERS
  prow/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#8740 update netd yaml to latest version
  config/jobs/kubernetes/sig-network/ci-e2e-gce-netd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8629 Create override plugin
  prow/github/client.go
  prow/github/types.go
  prow/hook/events.go
  prow/pjutil/pjutil.go
  prow/plugins/BUILD.bazel
  prow/plugins/override/BUILD.bazel
  prow/plugins/override/override.go
  prow/plugins/override/override_test.go
  prow/plugins/trigger/trigger.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8605 Utility to give prow access to other clusters
  prow/BUILD.bazel
  prow/cmd/mkbuild-cluster/BUILD.bazel
  prow/cmd/mkbuild-cluster/README.md
  prow/cmd/mkbuild-cluster/main.go
  prow/cmd/mkbuild-cluster/main_test.go
  prow/cmd/plank/main.go
  prow/getting_started.md
  prow/kube/client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8642 port over rest of the jobs/config_test.py logic
  config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml
  config/tests/jobs/jobs_test.go
Labels: approved, area/jobs, cncf-cla: yes, lgtm, size/M, ¯\_(ツ)_/¯

#8643 create welcome plugin
  prow/plugins/BUILD.bazel
  prow/plugins/plugins.go
  prow/plugins/welcome/BUILD.bazel
  prow/plugins/welcome/welcome.go
  prow/plugins/welcome/welcome_test.go
Labels: approved, area/prow, cncf-cla: yes, lgtm, size/L

#8507 Make Tide omit PRs failing GitHub contexts from the pool.
  prow/config/tide.go
  prow/config/tide_test.go
  prow/tide/status.go
  prow/tide/tide.go
  prow/tide/tide_test.go
Labels: approved, area/prow, cncf-cla: yes, kind/bug, lgtm, size/XL

#8749 Fixing the github location for the --repo for charts
  config/jobs/helm/charts/charts.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8751 Turn on some automation for the new cluster-api-provider-gcp repository.
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8713 migrate upgrade jobs to their own configs
  config/jobs/kubernetes/sig-cluster-lifecycle/OWNERS
  config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gce.yaml
  config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gke.yaml
  jobs/config.json
  jobs/env/ci-kubernetes-e2e-gce-gci-latest-upgrade-etcd.env
  jobs/env/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new.env
  jobs/env/ci-kubernetes-e2e-gce-new-master-upgrade-cluster.env
  jobs/env/ci-kubernetes-e2e-gce-new-master-upgrade-master.env
  prow/config.yaml
Labels: approved, area/jobs, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XXL

#8709 update docs on how to create new jobs
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8755 fix calico env vars for netd testgrid
  config/jobs/kubernetes/sig-network/ci-e2e-gce-netd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8754 Add initial config for kubernetes-sigs/cluster-api-provider-aws
  config/jobs/kubernetes-sigs/cluster-api-provider-aws/OWNERS
  config/jobs/kubernetes-sigs/cluster-api-provider-aws/cluster-api-provider-aws-presubmits.yaml
  prow/config.yaml
  prow/plugins.yaml
  testgrid/cmd/configurator/config_test.go
  testgrid/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8757 Update the image name used for the cluster-api tests.
  prow/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8759 aws-janitor: chunk deletions into batches of 1000
  maintenance/aws-janitor/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S
